# Generated by Django 4.2.4 on 2023-08-22 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fingerprint_path',
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_10',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_3',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_4',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_5',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_6',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_7',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_8',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fingerprint_9',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
