# Generated by Django 4.2.4 on 2023-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fingerprint_path', models.CharField(max_length=255)),
                ('face_path', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profiles', models.ManyToManyField(to='playground.profile')),
            ],
        ),
    ]
