# Generated by Django 4.2.4 on 2023-08-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_profile_fingerprint_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fingerprint_9',
            field=models.TextField(),
        ),
    ]
